### ISSUE TITLE
Collection variables not loading

### ISSUE THREAD

**Issue by jbyrne6** [podaac/hitide-ui#38]
### Bug

- when clicking on collection metadata variables don't show up other than "all"
- when clicking on the "Select Extraction Variables" only "all" shows up and not the other in the collection of the granule

**Comment by jbyrne6** [comment]
Submitting a bug fix to CMR Graphql. The bug prevents multiple variables to be queries at the same time in certain cases.

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test HiTIDE in UAT.  Should be able to list and subset variables like expected.
This should be release 4.16.2-rc.1.  Verify About and Release Notes pages too.
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (UAT) **4.16.2-rc.1**: 

**Test Failed**;
Dataset/Extraction Variables still default to 'all'  for cloud collections:


![111](https://github.com/podaac/hitide-ui/assets/57456095/d8fd36c9-8f9f-494c-ac41-bd0b5ca375df)
![113](https://github.com/podaac/hitide-ui/assets/57456095/c8dc85fe-627a-4d57-bf1e-1b61f5f30103)

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl   I just tried this again and it works for me.  Can you try it again?  Maybe clear your cache?

@jbyrne6 Can you help David with this?  It should work in UAT now.  Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**UAT**) 4.16.2-rc.1:
l2ss-py:2.7.0rc1
HiTIDE Profile v4.10.0-rc.1

Re-tested today,  the collection metadata variables are now showing as expected in HiTIDE UAT for cloud collections.

**_Test Complete_**

**Comment by jamesfwood** [comment]
Thanks @davidcolemanjpl !  This has been deployed to OPS.  V4.16.2.
Can you test this in OPS too?
Can you test that the variable subsetting works also?

Always remember to reset your cache too before testing.
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**OPS**) 4.16.2:
l2ss-py:2.7.0
HiTIDE Profile v4.10.0
concise: v0.7.0

Firefox v121.0.1 (64-bit)
Safari v17.0 (18616.1.27.111.22, 18616)
Chrome v120.0.6099.199 (Official Build) (arm64)

**_Test Complete_** 

Verified that collection variables are currently loading as expected in HiTIDE OPS UI.  
Variable subsetting now functions as expected in the HiTIDE OPS UI.
