### ISSUE TITLE
Image broken for certain cloud dataset icons: Metadata & Granule Availability

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#42]
Details here:
https://jira.jpl.nasa.gov/browse/PODAAC-5621

**Comment by jamesfwood** [comment]
@jbyrne6 Hitide UI will need to pull the image URL from CMR.  As we discussed on Slack. 
Sound good?

**Comment by jamesfwood** [comment]
@jbyrne6 Can you look at maybe trying to grab the URL from CMR instead?  That seems to be more reliable way, and that url you put in there seems like it could change.

In CMR it looks like this:

{
"Description": "Thumbnail",
"URLContentType": "VisualizationURL",
"Type": "GET RELATED VISUALIZATION",
"URL": "https://podaac.jpl.nasa.gov/Podaac/thumbnails/AMSR2-REMSS-L2P-v8.2.jpg"
},

You can grab the RelatedURL with description Thumbnail, and then return the URL.

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test HiTIDE in UAT for this issue.  Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**UAT**) v_4.17.0-RC.1_:


The following JASON_CS_S6A cloud-collections currently display the broken Metadata & Granule Availability image issue in HiTIDE (UAT) UI venue:

JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F
JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F
JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F
JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F
JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F
JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F
JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F
JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F
JASON_CS_S6A_L2_AMR_RAD_NRT
JASON_CS_S6A_L2_AMR_RAD_STC

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl 
Please test this again in Hitide UAT (VERSION 4.17.0-RC.3)
It should all be fixed now.

Work with @jbyrne6 too regarding the External Links.  Some of the private collections is ok to not be found.

Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**UAT**) v**_4.17.0-RC.3_**:

**Test Complete** 

Verified that the following JASON_CS_S6A cloud-collections no longer display the _broken_ Metadata & Granule Availability image issue in HiTIDE (UAT) UI venue. 
An 'Image Not Available' image now displays in UI for the 10 'JASON_CS_S6A_L2' cloud datasets accordingly:

JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F - 'Image Not Available'
JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F - 'Image Not Available'
JASON_CS_S6A_L2_AMR_RAD_NRT - 'Image Not Available'
JASON_CS_S6A_L2_AMR_RAD_STC - 'Image Not Available'

![JASON_CS_S6A_L2 image-metadatandGranule-Availability-PIC1](https://github.com/podaac/hitide-ui/assets/57456095/edba193f-5202-4a22-a013-d346013f374f)

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test again in Hitide OPS and can you Complete your JIRA ticket for this?
Thanks!

**Comment by davidcolemanjpl** [comment]
**HiTIDE UI (OPS) v4.17.1**

**_Test Complete_**
