### ISSUE TITLE
External Link for SWOT_L2 datasets not properly navigating user to landing page

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#43]
Details here:
https://jira.jpl.nasa.gov/browse/PODAAC-5864

**Comment by jamesfwood** [comment]
@jbyrne6 Be sure that all the SWOT 2.0 collections are working properly also.

**Comment by jamesfwood** [comment]
@jbyrne6 Ask Jack what he thinks we should do about this.  And for each version.

**Comment by jbyrne6** [comment]
@jjmcnelis pointed out that the links that were not working are for collections that are not available to the public. A majority of users don't have access to those non public collections so this bug won't effect a majority of users. It is not the responsibility of the TVA team to make the collections public so no action is needed from the TVA team to remedy this issue.

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test in HiTIDE UAT.
Thanks!

**Comment by jamesfwood** [comment]
It's ok for some collections to be missing the External links.

**Comment by davidcolemanjpl** [comment]
note: I will need to figure out  or get more deets about which specific SWOT L2 collections should have the External links fix

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (UAT) v**_4.17.0-RC.3_**:

All SWOT L2 collection External links in HiTIDE (UAT) UI still do not navigate user properly to the respective landing pages in WebPortal:

SWOT_L2_LR_SSH_BASIC_1.0 – still an issue - External Link for SWOT_L2 dataset not properly navigating user to SWOT collection landing page -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_BASIC_1.0

SWOT_L2_LR_SSH_BASIC_1.1 – still an issue - External Link for SWOT_L2 dataset not properly navigating user to SWOT collection landing page -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_BASIC_1.1

SWOT_L2_LR_SSH_BASIC_2.0 –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_BASIC_2.0

SWOT_L2_LR_SSH_EXPERT_1.0 –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_EXPERT_1.0

SWOT_L2_LR_SSH_EXPERT_1.1 –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page as expected -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_EXPERT_1.1

SWOT_L2_LR_SSH_EXPERT_2.0 –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page as expected -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_EXPERT_2.0

SWOT_L2_LR_SSH_WINDWAVE_1.0 – –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page as expected -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_WINDWAVE_1.0

SWOT_L2_LR_SSH_WINDWAVE_1.1 –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page as expected -
http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_WINDWAVE_1.1

SWOT_L2_LR_SSH_WINDWAVE_2.0 – –  still an issue - External Link for SWOT_L2 dataset not properly navigating user to landing page as expected - "Found 0 matching dataset(s)"  - http://podaac.jpl.nasa.gov/dataset/SWOT_L2_LR_SSH_WINDWAVE_2.0

example:
![external link not locating dataset landing page-pic1](https://github.com/podaac/hitide-ui/assets/57456095/f21fb96e-dbfc-4e43-ae73-9d29ac0b9997)

**Comment by jamesfwood** [comment]
Will retest this when these collections become publicly available.

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test again.  The 2.0 collections should work now.  Also, I talked with @jjmcnelis about the 1.0 and 1.1 collections.  It is expected for the external link to not be found in the portal because portal doesn't show privileged collections.  So this ticket should go to Complete unless you see a reason why it should not.
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**UAT**)  v**4.17.0-RC.6**

Verified that the SWOT_L2_LR  version **v2.0** collection External Links are now properly navigating the user to landing page  accordingly:

_SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0_

**_Test Complete_**

note: the SWOT_L2_LR  v1.0 and v1.1 collections still has issue. 
Per DEV, ..."the external link to not be found in the portal because portal doesn't show privileged collections"

**Comment by jamesfwood** [comment]
Thanks @davidcolemanjpl.  Can you close out your JIRA ticket for this too?
Thanks!
