### ISSUE TITLE
Footprints and Thumbnail images remain on map in UI after the Footprint and Thumbnail image icons were deselected

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#44]
Details here:

https://jira.jpl.nasa.gov/browse/PODAAC-5545

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test this in HITIDE UI 4.17.1 in UAT.
Thanks!

**Comment by davidcolemanjpl** [comment]
**_HiTIDE (UAT) v4.17.1-RC.1_**

Confirmed that this anomaly is  no longer an issue in HiTIDE UAT.

**_Test Complete_**

**Comment by jamesfwood** [comment]
@davidcolemanjpl please test again in OPS.
Thanks!

**Comment by davidcolemanjpl** [comment]
**_HiTIDE (OPS) v4.17.1_**

Confirmed that this is no longer an issue in HiTIDE OPS.

**_Test Complete_**
