### ISSUE TITLE
Server Error displays when selecting certain cloud enabled datasets

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#46]
Details here:

https://jira.jpl.nasa.gov/browse/PODAAC-5758

**Comment by jamesfwood** [comment]
@davidcolemanjpl Hi David.  Please test this again.  Rest all collections in HITIDE OPS and UAT now.  Also, some of them in your list were old and removed from HiTIDE.  Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE (OPS): 4.17.0 (_60 matching datasets_) - OKAY
HiTIDE (UAT): 4.17.0-RC.6 (_83 matching datasets_) - OKAY

Confirmed that server error NO longer displays in HiTIDE UIs when cloud datasets are selected


**_Test Complete_**
