### ISSUE TITLE
Distinguish collections without Spatial Resolution (Not Applicable) versus an Error (Not Available)

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide-ui#48]
We need to come up with a way of knowing what collections shouldn't have Spatial Resolution and mark them as Not Applicable.  Need to talk with Jack more on this.

Notes from Jimmy:
With the code right now all I can tell is if the dataset resolution is missing. It doesn't inform me if it is missing because of an error or because it is not applicable to a dataset. If I had a formal list of the datasets where it is not applicable I would be able to cross reference it to differentiate between not applicable and not available. The ticket would be to implement this list for cross referencing. This was my thought process but let me know if I should be going a different route.

**Comment by jbyrne6** [comment]
[HiTIDE Missing Resolution Datasets.xlsx](https://github.com/podaac/hitide-ui/files/14273907/HiTIDE.Missing.Resolution.Datasets.xlsx)

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test in HiTIDE UAT
Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (UAT) **_v4.17.0-RC.3_**

**_Test Complete_**

Verified that the following cloud-collections that have no associated Spatial Resolution are listed as Not Applicable (in DATASET INFORMATION) in HiTIDE UI accordingly (cloud-datasets that are supposed to be missing spatial resolution):

AQUARIUS_L2_SSS_CAP_V5 - Spatial Resolution = Not Applicable
AQUARIUS_L2_SSS_V5 - Spatial Resolution = Not Applicable
JASON-1_L2_OST_GPN_E - Spatial Resolution = Not Applicable
JASON-1_L2_OST_GPR_E - Spatial Resolution = Not Applicable
JASON-1_L2_OST_GPS_E - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_HR_RED_OST_NRT_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F -  Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_HR_STD_OST_NRT_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_LR_RED_OST_NRT_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_LR_STD_OST_NRT_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_AMR_RAD_NRT - Spatial Resolution = Not Applicable
JASON_CS_S6A_L2_AMR_RAD_STC - Spatial Resolution = Not Applicable
MERGED_TP_J1_OSTM_OST_CYCLES_V42 - Spatial Resolution = Not Applicable
SWOT_L2_NALT_GDR_SSHA_1.0 - N/A - cloud-collection not in HiTIDE UAT
SWOT_L2_NALT_IGDR_SSHA_1.0 - N/A - collection not in HiTIDE UAT
SWOT_L2_NALT_OGDR_SSHA_1.0 - N/A - collection not in HiTIDE UAT
TOPEX_POSEIDON_GDR_F - Spatial Resolution = Not Applicable

[HiTIDE Missing Resolution Datasets - latest.xlsx](https://github.com/podaac/hitide-ui/files/14349566/HiTIDE.Missing.Resolution.Datasets.-.latest.xlsx)
